---
title: "Distribuciones de variables Discretas."
author: "Martí Paredes"
subtitle: 'Apuntes de videos - Semana 3 del 8 de marzo  al  14 de marzo '
output:
  pdf_document: default
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

Aplicaremos las variables discretas sin disticion al tipo de población que estamos
tratando o a una funión, ya puede ser de probabilidad, de densidad etc ...

Las variables discreatas són muy comunes en el dia a dia.\

# Video 1: Distribución de Bernouilli.

Desigaremos el espacio muestral como exito o fracaso que llamaremos "E" y "F" respectivamente.

Por lo tanto nuestro espacio muestral queda tal que: $$Omega = {(Exito,\ Fracaso)} = {(E,\ F)}.$$

Suponemos que la probabilidad de éxito és: $P(E) = p$ y por consiguiente $P(F) =\ 1-p \ = \ q$.

Consideramos la siguiente aplicación sobre el espacio muestral:
$$X:Omega = {(E,\ F}) \rightarrow \mathbb R \  \ definiendo\ \ X(E) = 1 \ \ y \ \ X(F) = 0.$$  
Entonces su función de proabilidad se define como :

Y su función de densidad queda tal que:

Estas forumlas y distribuciones podemos calcularlas directamente con el la función base de R `binom` el qual tiene las funciones de `pbinom()` y `dbinom()` para calcular la función de probabilidad y de densidad.

Estas funciones contan de 3 argumentos:

```
_binom(x, size, prob) 
          x: el valor a buscar.
          size: número de repeticiones a realizar. 
          prob: probabilidad de éxito.  
``` 
Para el estudio de una distribucion de Bernoulli usaremos $x\ \epsilon \ [0,1]$ y fijaremos el número de repeticiones a 1. Nos quedaria una función tal que `_binom([0,1],size=1,prob='prob. de éxito')`.

## Resumen distribución de probabilidad y distribución.

La función de distribución se define como $F_X(x)$, en otras palabras, la probabilidad de que X sea igual a un número, $F_X(x=X)$.

Mientras la función de probabilidad se define como la probabilidad de que un número tome el valor igual o inferior a X, $F_X(x \leq X)$, en este caso como tratamos con variables discretas que un número sea inferior a X, $F_X(x < 3)$, nos da la misma probabilidad de menor o igual que X-1, $F_X(x \leq 2)$.

