---
title: "Ejercicios Tema 1 : Probabilidad."
author: "Martí Paredes Salom"
date: "Empezado el 08-03-2021"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

### Ejercicios de Espacios muestrales y sucesos.

1. Se seleccionan al azar tres cartas sin reposición de una baraja que contiene 3 cartas rojas, 3 azules,
3 verdes y 3 negras. Especifica un espacio muestral para este experimento y halla todos los sucesos
siguientes:

* $A$ = “Todas las cartas seleccionadas son rojas”
* $B$ = “Una carta es roja, una es verde y otra es azul”
* $C$ = “Salen tres cartas de colores diferentes”

$$\Omega = \{R1,R2,R3,A1,A2,A3,V1,V2,V3,N1,N2,N3\}$$

**Solución A**: Tenemos 3 colores y tres cartas diferentes, entonces una letra por color y un número por bola. 

$A = \{(R1, R1, R2),(R2, R3, R3),(R2, R3, R1),(R3, R1, R2),(R3, R2, R3),(R1, R2, R1)\}$

**Solución B**: Tenemos el cardinal anterior, 6, ahora en vez de cartas repetidas tenemos cartas de colores diferentes, por lo tanto $3^3$ possibles combinaciones. 

Por lo tanto $B = 6 \cdot 3^3 = `r 6*3^3`$ possibles combinaciones totales.

**Solución C**: Ahora en vez de 3 colores especificos tenemos trios de colores no repetidos. Por lo tanto 4 colores diferentes. 

Por lo tanto $C = 6 \cdot 3^3 \cdot 4 = `r 6*3^3*4`$ possibles trios de colores diferentes.\

### Ejercicios de probabilidad.

1. Se lanzan al aire dos monedas iguales. Hallar la probabilidad de que salgan dos caras iguales.

**Solución** : Primero definimos el espacio muestral para dos lanzamientos.
$$\Omega = {(CC,C+,+C,++)}$$
Y ahora hacemos cassos favorables entre cassos possibles. $$P(CC) = \frac{Cassos\ favorables}{Cassos\ possibles} = \frac{CC}{{CC,C+,+C,++}}=\frac{1}{4}$$ \

2. Suponer que se ha trucado un dado de modo que la probabilidad de que salga un número es proporcional
al mismo.

* Hallar la probabilidad de los sucesos elementales, de que salga un número par y también de que
salga un número impar.
* Repetir el problema pero suponiendo que la probabilidad de que salga un determinado número es
inversamente proporcional al mismo.